import { Project } from "@/types/project";

export const projectsData: ReadonlyArray<Project> = [
  {
    slug: "portfolio-lennin",
    title: "My Portfolio",
    subtitle: "And is a great portfolio",
    date: "2025-09-08",
    description: "Portfolio that shows my most relevant projects with a clean design and fast navigation.",
    tags: ["react", "frontend", "personal"],
  },
  {
    slug: "text-edit-vps",
    title: "Text Edit App",
    subtitle: "Lightweight editor running on my VPS",
    date: "2025-07-10",
    description: "A simple collaborative text editor deployed on my VPS with Docker, Next.js frontend, Django backend, and PostgreSQL.",
    tags: ["fullstack", "nextjs", "django", "postgresql", "docker"],
  },
  {
    slug: "git-progress-sprites",
    title: "Git Progress Sprite Maker",
    subtitle: "Commit daily, unlock a sprite",
    date: "2025-07-28",
    description: "Web app that rewards daily git commits with progress on ASCII art Pokémon sprites. Uses Prisma and Next.js.",
    tags: ["nextjs", "deno", "docker", "postgresql"],
  },
  {
    slug: "album-ranker",
    title: "Album Ranker",
    subtitle: "Rate and rank music albums",
    date: "2025-06-15",
    description: "Personal tool to rank, compare, and visualize favorite albums using tier-lists and charts.",
    tags: ["react", "personal"],
  },
  {
    slug: "nidnib-notebook",
    title: "Nidnib Modular Notebook",
    subtitle: "Eco-friendly customizable paper system",
    date: "2025-03-18",
    description: "A modular notebook system with custom pages and slots. Includes crowdfunding prep and branding design.",
    tags: ["design"],
  },
  {
    slug: "tasky-manager",
    title: "Tasky",
    subtitle: "Simple task manager",
    date: "2025-04-07",
    description: "A minimalistic to-do manager with Java backend and PostgreSQL, designed for personal productivity.",
    tags: ["postgresql", "fullstack"],
  },
  {
    slug: "fighting-game-prototype",
    title: "FightingGame",
    subtitle: "2D grappler prototype",
    date: "2025-02-05",
    description: "A small prototype of a 2D fighting game inspired by grapplers. Built with C# and later ported to Kotlin.",
  },
  {
    slug: "hadaly-payment-platform",
    title: "Hadaly Payment Platform",
    subtitle: "Stripe-powered subscription system",
    date: "2025-04-12",
    description: "Stripe Embedded Price Tables with custom subscription upgrades. Contributed as part of Hadaly's platform.",
    tags: ["frontend"],
  },
  {
    slug: "doom-city-architect",
    title: "Doom City Architect",
    subtitle: "Architecture → Doom levels",
    date: "2024-12-31",
    description: "Experimental app that transforms photos of city architecture into procedurally generated Doom levels.",
    tags: ["fun", "ai"],
  },
  {
    slug: "ai-noir-blog",
    title: "AI NOIR Blog",
    subtitle: "Retro web 90s-style blog",
    date: "2025-04-13",
    description: "A nostalgic retro blog with AI-written noir stories, hosted with no-code tools and styled like early 2000s websites.",
    tags: ["frontend"],
  },
] as const;