import { Project } from "@/types/project";

export const projectsData: ReadonlyArray<Project> = [
  {
    slug: "portfolio-lennin",
    title: "My Portfolio",
    subtitle: "And is a great portfolio",
    date: "2025-09-08",
    description: "Portfolio that shows my most relevant projects with a clean design and fast navigation.",
    imageUrl: "images/portfolio-lennin.png",
    tags: ["react", "frontend", "personal"],
    repoUrl: "https://github.com/Lenninssp/Lennin-portfolio",
    demoUrl: "https://lenninssp.github.io/Lennin-portfolio/",
  },
  {
    slug: "text-edit-vps",
    title: "Text Edit App",
    subtitle: "Lightweight editor running on my VPS",
    date: "2025-07-10",
    imageUrl:"images/text-edit.png",
    description: "A simple collaborative text editor deployed on my VPS with Docker, Next.js frontend, Django backend, and PostgreSQL.",
    tags: ["fullstack", "nextjs", "django", "postgresql", "docker"],
    repoUrl: "https://github.com/Lenninssp/crocro-noteapp",
  },
  {
    slug: "git-progress-sprites",
    title: "Git Progress Sprite Maker",
    subtitle: "Commit daily, unlock a sprite",
    date: "2025-07-28",
    imageUrl: "images/git-sprite.png",
    description: "Web app that rewards daily git commits with progress on ASCII art Pokémon sprites. Uses Prisma and Next.js.",
    tags: ["nextjs", "deno", "docker", "postgresql"],
    repoUrl: "https://github.com/Lenninssp/MagnusGit",
  },
  {
    slug: "album-ranker",
    imageUrl: "images/album-ranker.jpg",
    title: "Album Ranker",
    subtitle: "Rate and rank music albums",
    date: "2025-06-15",
    description: "Personal tool to rank, compare, and visualize favorite albums using tier-lists and charts.",
    tags: ["react", "personal"],
    repoUrl: "https://github.com/Lenninssp/Album-Ranker"
  },
  {
    slug: "nidnib-notebook",
    title: "Nidnib Modular Notebook",
    subtitle: "Eco-friendly customizable paper system",
    date: "2025-03-18",
    description: "A modular notebook system with custom pages and slots. Includes crowdfunding prep and branding design.",
    tags: ["design"],
  },
  {
    slug: "tasky-manager",
    title: "Tasky",
    subtitle: "Simple task manager",
    date: "2025-04-07",
    description: "A minimalistic to-do manager with Java backend and PostgreSQL, designed for personal productivity.",
    tags: ["postgresql", "fullstack"],
    imageUrl: "images/tasky.png",
    repoUrl: "https://github.com/Lenninssp/crocro-noteapp",
  },
] as const;